---
title: "DataReplication_Steven"
author: "Steven"
date: "3/24/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r cleaningdata}
#Pick a small set of the descriptive and inferential stats they do, plus a visualization, and try to replicate those

library(tidyverse)
library(readxl)
f<-"data/neurogenesisdata.xlsx"
d<-read_excel(f,sheet=1,col_names=TRUE)
head(d)
names(d)

#Creating seperate data frames for large dataset, and removing the original header 
subjectdata<-select(d,...1,...2,...3,...4,...5,...6,...7,...8,...9,...10,...11,...12,...13,...14,...16)
colnames(subjectdata) <- as.character(unlist(subjectdata[1,]))
subjectdata = subjectdata[-1, ]

GCLmm<-select(d,"GCL cells/mm3",...18,...19,...20,...21)
colnames(GCLmm) <- as.character(unlist(GCLmm[1,]))
GCLmm = GCLmm[-1, ]
GCLmm<-bind_cols(subjectdata,GCLmm)
GCLmm<-rename(GCLmm,diagnosis="Clinical Diagnosis\r\n(CogDx)")

SGLmm<-select(d,"SGL cells/mm3",...23,...34,...25,...26)
colnames(SGLmm) <- as.character(unlist(SGLmm[1,]))
SGLmm = SGLmm[-1, ]
SGLmm<-bind_cols(subjectdata,SGLmm)
SGLmm<-rename(SGLmm,diagnosis="Clinical Diagnosis\r\n(CogDx)")

DGmm<-select(d,"Dentate Gyrus Total cells/mm3",...28,...29,...30,...31,...32,...33,...34)
colnames(DGmm) <- as.character(unlist(DGmm[1,]))
DGmm = DGmm[-1, ]
DGmm<-bind_cols(subjectdata,DGmm)
DGmm<-rename(DGmm,diagnosis="Clinical Diagnosis\r\n(CogDx)")

GCLtot<-select(d,"GCL Total Cells",...36,...37,...38,...39)
colnames(GCLtot) <- as.character(unlist(GCLtot[1,]))
GCLtot = GCLtot[-1, ]
GCLtot<-bind_cols(subjectdata,GCLtot)
GCLtot<-rename(GCLtot,diagnosis="Clinical Diagnosis\r\n(CogDx)")

SGLtot<-select(d,"SGL Total Cells",...41,...42,...43,...44)
colnames(SGLtot) <- as.character(unlist(SGLtot[1,]))
SGLtot = SGLtot[-1, ]
SGLtot<-bind_cols(subjectdata,SGLtot)
SGLtot<-rename(SGLtot,diagnosis="Clinical Diagnosis\r\n(CogDx)")

DGtot<-select(d,"Dentate Gyrus Total Cells",...46,...47,...48,...49,...50,...51,...52)
colnames(DGtot) <- as.character(unlist(DGtot[1,]))
DGtot = DGtot[-1, ]
DGtot<-bind_cols(subjectdata,DGtot)
DGtot<-rename(DGtot,diagnosis="Clinical Diagnosis\r\n(CogDx)")

```

## Figure 1

```{r Figure 3, echo=FALSE}
library(ggplot2)
theme_set(theme_bw())

#Changing discrete variable to continuous 
SGLmm$Nestin <- as.numeric(as.character(SGLmm$Nestin))

#Graph
g<-ggplot(SGLmm, aes(x = diagnosis, fill = diagnosis, y = Nestin)) +
  geom_dotplot(binaxis = "y", stackdir = "center", position = "dodge",binwidth=100) +
  labs(title="Subgranular Layer", 
       y="Nestin+ Cells per mm^3") +
  ylim(0,5000)
g
  
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
